// <auto-generated />
using System;
using DbApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908221513_CriadoFuncionarios")]
    partial class CriadoFuncionarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbApi.Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("codCli");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("AtivoCli");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("endCli");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomeCli");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("telefoneCli");

                    b.HasKey("Id");

                    b.ToTable("Tb_clientes", (string)null);
                });

            modelBuilder.Entity("DbApi.Models.Funcionario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("idFuncionario");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("enderecoFuncionario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nomeFuncionario");

                    b.HasKey("Id");

                    b.ToTable("Tb_funcionario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
